spring.application.name=Counsellor-Portal

# Database connection settings
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable the web browser console view
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate settings to automatically create tables from Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



